[Journal]
Seal                = true
Audit               = true
Storage             = volatile
ReadKMsg            = true
Compress            = true
SplitMode           = uid
MaxFileSec          = 12h
SystemMaxUse        = 64M
MaxLevelStore       = info
ForwardToSyslog     = false
MaxRetentionSec     = 12h
SystemMaxFileSize   = 32M
