[Resolve]
Cache                       = true
LLMNR                       = false
DNSSEC                      = allow-downgrade
DNSOverTLS                  = false
FallbackDNS                 = 127.0.0.1
ReadEtcHosts                = true
MulticastDNS                = false
DNSStubListener             = false
ResolveUnicastSingleLabel   = false
