[Manager]
LogTime                         = false
LogColor                        = true
DumpCore                        = false
LogLevel                        = warning
LogTarget                       = journal-or-kmsg
ShowStatus                      = auto
NUMAPolicy                      = default
CrashShell                      = false
CrashAction                     = freeze
LogLocation                     = false
ProtectSystem                   = auto
CrashChangeVT                   = false
NoNewPrivileges                 = false
DefaultTasksMax                 = 15%
DefaultOOMPolicy                = stop
StatusUnitFormat                = description
KExecWatchdogSec                = off
DefaultRestartSec               = 100ms
DefaultLimitNOFILE              = 1024:524288
RuntimeWatchdogSec              = 0
ShutdownWatchdogSec             = 0
DefaultIOAccounting             = false
DefaultIPAccounting             = false
DefaultStandardError            = inherit
DefaultCPUAccounting            = false
DefaultTimeoutStopSec           = 30s
DefaultStandardOutput           = journal
CtrlAltDelBurstAction           = reboot-force
DefaultTimeoutStartSec          = 30s
DefaultStartLimitBurst          = 5
DefaultTasksAccounting          = true
DefaultTimerAccuracySec         = 1min
DefaultMemoryAccounting         = true
DefaultBlockIOAccounting        = false
DefaultStartLimitIntervalSec    = 10s
